# Generated by Django 4.2.1 on 2023-12-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_consultation_ordonance'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='profession',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
